<div class="header_l">
  <div class="header_logo">
    <h1>
      <a href="/">
        <picture>
          <source media="(max-width: 768px)" srcset="./assets/img/logo_sp.png" />
          <img src="./assets/img/logo_pc.png" alt="" />
        </picture>
      </a>
    </h1>
    <div class="header_logo_mul">
      <div class="menu_icon show_sp" id="menu_icon">
        <span class="menu_icon_in">
          <span class="menu-trigger">
            <span></span>
            <span></span>
            <span></span>
          </span>
          <i>メニュー</i>
        </span>
      </div>
      <div class="ic_line show_sp">
        <a href="">
          <img src="./assets/img/ic_line.png" alt="">
          <span>LINEで<br>お問合せ</span>
        </a>
      </div>
      <div class="ic_tel show_sp">
        <a href="tel:050-8882-6655">
          <img src="./assets/img/ic_tel.png" alt="">
          <span>電話で<br>お問合せ</span>
        </a>
      </div>
    </div>
  </div>
</div>
<div class="header_r" id="header_r">
  <div class="header_nav" id="header_nav">
    <ul>
      <li class="active"><a href="/"><span class="show_pc">TOP</span><span class="show_sp">ホーム</span></a></li>
      <li><a href="/advantage.html">クラウドWiFiの特徴</a></li>
      <li><a href="/plan.html">端末詳細・料金プラン</a></li>
      <li><a href="/overseas.html">海外利用について</a></li>
      <li><a href="/flow.html">ご利用の流れ</a></li>
      <li><a href="/faq.html">よくあるご質問</a></li>
      
    </ul>
  </div>
  <div class="header_m_ex show_sp">
    <ul>
      <li><a target="_blank" href="https://wifi-tokyo-rentalshop.com/cc/contact"><i></i>お問合せ</a></li>
      <li><a target="_blank" href="https://www.wifi-tokyo-rentalshop.com/terms-of-service/"><i></i>特定商取引法の表記</a></li>
      
      <li><a target="_blank" href="https://wifi-tokyo-rentalshop.com/cc/help/privacy"><i></i>個人情報保護方針</a></li>
      <li><a target="_blank" href="https://wifi-tokyo-rentalshop.com/cc/help/tradelaw"><i></i>利用規約</a></li>
    </ul>
  </div>
  <div class="header_social">
    <span class="show_sp">SHARE</span>
    <ul>
      <li>
        <a href="#facebook">
          <picture>
            <source media="(max-width: 768px)" srcset="./assets/img/ic_fb_sp.png" />
            <img src="./assets/img/ic_fb_pc.png" alt="" />
          </picture>
        </a>
      </li>
      <li>
        <a href="#twitter">
          <picture>
            <source media="(max-width: 768px)" srcset="./assets/img/ic_tw_sp.png" />
            <img src="./assets/img/ic_tw_pc.png" alt="" />
          </picture>
        </a>
      </li>
      <li>
        <a href="#instagram">
          <picture>
            <source media="(max-width: 768px)" srcset="./assets/img/ic_ig_sp.png" />
            <img src="./assets/img/ic_ig_pc.png" alt="" />
          </picture>
        </a>
      </li>
    </ul>
  </div>
  <a class="show_pc h_contact" target="_blank" href="https://wifi-tokyo-rentalshop.com/cc/products/detail/4">お申込みはこちら<i></i></a>
</div>