<h2 class="t_ttl2"><small>PLAN</small>料金プラン</h2>
<h3>
  <picture>
    <source media="(max-width: 768px)" srcset="./assets/img/plan_txt_sp.png" />
    <img src="./assets/img/plan_txt_pc.png" alt="" />
  </picture>
</h3>
<p class="txt01">クラウド WiFi の料金プランは<br class="show_sp"> 「月額 3,380 円プラン 」 の 1 つだけ。<br> シンプルで分かりやすく、<br class="show_sp">複雑なプランや料金・特典などが異なる <br>複数のプランから選択しなくても OKです。</p>
<a class="t_btn" href="./overseas.html"><span>料金プランを詳しく見る</span></a>