<?php

namespace Customize\Repository;

use Customize\Entity\Withdraw;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Eccube\Repository\AbstractRepository;

/**
 * WithdrawRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WithdrawRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Withdraw::class);
    }

    public function getWithdrawSecret($Order){
        return $this->findOneBy(['Order' => $Order, 'withdraw_type' => 1, 'visible' => 1]);
    }

    public function getWithdrawPlan($Order){
        return $this->findOneBy(['Order' => $Order, 'withdraw_type' => 2, 'visible' => 1]);
    }
}
